---
  - hosts: localhost
    #sudo: True
    user: centos
    tasks:
    become: true
   
    roles:
    - UPDATE
    - NGINX
    - STATIC_WEBSITE
    - TOMCAT
    - MYSQL
    - PHP
    - WORDPRESS
    - MAGENTO
    - CONF_FOR_NGINX
