- name: COPY php.ini CONFIGURATION
  template: src=php.ini dest=/etc/php.ini

- name: INSTALL PYTHON-PIP
  yum:
    name: python-pip
    state: latest

- name: MAKE SURE PYMYSQL IS PRESENT
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present

- name: CREATE MAGENTO DATABASE
  mysql_db:
    name: magentodb
    state: present

- name: CREATE MAGENTO USER
  mysql_user:
    name: magentouser
    password: Magento123@
    priv: magentodb.*:ALL
    host: "localhost"
    state: present

- name: DOWNLOAD COMPOSER
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer

- name: INSTALL COMPOSER
  shell: cat /tmp/installer | php -- --install-dir=/usr/bin
  args:
    creates: /usr/bin/composer

- name: RENAME composer.phar TO composer
  shell: mv /usr/bin/composer.phar /usr/bin/composer
  args:
    creates: /usr/bin/composer

- name: MAKE COMPOSER EXECUTABLE
  file: 
    path: /usr/bin/composer
    mode: a+x
    state: file

- name: DOWNLOAD MAGENTO
  get_url:
    url: https://github.com/magento/magento2/archive/2.1.zip
    dest: /var/www/html

- name: CREATING DIRECTORY IF THERE IS NO
  file:
    path: /var/www/html/magento2
    state: directory
    mode: '755'
    owner: nginx
    group: nginx
    recurse: yes

- name: EXTRACTING FILE MAGENTO
  unarchive:
    src: /var/www/html/magento2-2.1.zip
    dest: /var/www/html/
    remote_src: yes
    
- name: SET FILE/DIRECTORY PERMISSIONS
  shell: find . -type f -exec chmod 644 {} \; && find . -type d -exec chmod 755 {} \; && find ./var -type d -exec chmod 777 {} \; && find ./pub/media -type d -exec chmod 777 {} \; && find ./pub/static -type d -exec chmod 777 {} \;
  args:
    chdir: /var/www/html/magento2-2.1

- name: COMPOSER INSTALL
  shell: composer install -v
  args:
    chdir: /var/www/html/magento2-2.1

#- name: COPY ARCHIVES
#  command: mv /var/www/html/magento2/magento2-2.1 /var/www/html/magento2

- name: INSTALL MAGENTO 2 FROM CLI
  shell: php /var/www/html/magento2-2.1/bin/magento setup:install \
    --backend-frontname=adminlogin \
    --key="biY8vdWx4w8KV5Q59380Fejy36l6ssUb" \
    --db-host="localhost" \
    --db-name="magentodb" \
    --db-user="magentouser" \
    --db-password="Magento123@" \
    --language="en_US" \
    --currency="USD" \
    --timezone="America/Sao_Paulo" \
    --use-rewrites=1 \
    --use-secure=0 \
    --base-url="http://loja-barbosa.barbosateam.tk" \
    --admin-user=adminuser \
    --admin-password=admin123@ \
    --admin-email=admin@newmagento.com \
    --admin-firstname=admin \
    --admin-lastname=user \
    --cleanup-database
  args:
    chdir: /var/www/html/magento2-2.1
#  when: mage2_installed.stat.exists == False

- name: PERMISSION OF APP/ETC
  shell: chmod 700 /var/www/html/magento2-2.1/app/etc

- name: PERMISSION RECURSSIVE OF NGINX-MAGENTO
  shell: chown -R nginx:nginx /var/www/html/magento2-2.1/

#- name: RESTART NGINX
#  notify: restart nginx
