---
# tasks file for UPDATE
- name: PACKAGES
  shell: sudo yum -y update
- name: "Instalar pre-requisitos [NGINX]"
  yum:
    name: epel-release
    state: latest

- name: Install basic packages
  package:
    name: ['vim','wget','unzip','curl','git']
    state: present

    
