---
# tasks file for MYSQL
- name: Install MySQL repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

- name: INSTALL MYSQL-CLIENT
  yum:
    name: mysql-community-client
    state: latest

- name: INSTALL MYSQL-SERVER
  yum:
    name: mysql-community-server
    state: latest

- name: INSTALL PYTHON-PIP
  yum:
    name: python-pip
    state: latest

#- name: CREATE MYSQL CONFIGURATION FILE
#  template: src=my.cnf.j2 dest=/etc/my.cnf
#  notify: restart mariadb

#- name: CREATE MARIADB LOGFILE
#  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: START MYSQL SERVICE
  service: name=mysqld state=started enabled=yes
