- name: INSTALL JAVA
  yum:
    name: java-1.7.0-openjdk-devel
    state: present

- name: ADD TOMCAT GROUP
  group:
    name: tomcat

- name: ADD TOMCAT USER
  user:
    name: tomcat
    group: tomcat
    home: /opt/tomcat/apache-tomcat-8.5.58
    createhome: no
    system: yes

- name: DOWNLOAD TOMCAT
  get_url:
    url: https://www.apache.org/dist/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz
    dest: /tmp

- name: CREATING DIRECTORY 'tomcat' IF THERE IS NO
  file:
    path: /opt/tomcat/apache-tomcat-8.5.58
    state: directory

- name: CREATING DIRECTORY 'bin' IF THERE IS NO
  file:
    path: /opt/tomcat/apache-tomcat-8.5.58/bin
    state: directory
    mode: '755'
    owner: tomcat
    group: tomcat
    recurse: yes

- name: EXTRACTING FILE TOMCAT
  unarchive:
    src: /tmp/apache-tomcat-8.5.58.tar.gz
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
#    creates: /opt/tomcat/apache-tomcat-8.5.58/bin
    remote_src: yes

#- name: PERMISSION OF ARCHIVE
#  command: cp . -R /opt/tomcat/apache-tomcat-8.5.58 /opt/tomcat

- name: PERMISSION OF ARCHIVE 'conf'
  command: sudo chmod -R g+r /opt/tomcat/apache-tomcat-8.5.58/conf

- name: PERMISSION OF ARCHIVE 'conf > g+x'
  command: sudo chmod g+x /opt/tomcat/apache-tomcat-8.5.58/conf

- name: PERMISSION OF ARCHIVE 'webapps' 'work' 'temp' 'logs'
  command: sudo chown -R tomcat /opt/tomcat/apache-tomcat-8.5.58/webapps/ /opt/tomcat/apache-tomcat-8.5.58/work/ /opt/tomcat/apache-tomcat-8.5.58/temp/ /opt/tomcat/apache-tomcat-8.5.58/logs/

#- name: PERMISSION OF ARCHIVE
#  shell: sudo useradd -M -s /bin/nologin -g tomcat -d /opt/tomcat tomcat

#- name: PROPERTY OF ARCHIVE
#  shell: sudo chgrp -R tomcat /opt/tomcat

#- name: PROPERTY OF ARCHIVE
#  shell: sudo chmod -R g+r conf

#- name: PROPERTY OF ARCHIVE
#  shell: sudo chmod g+x conf

- name: COPY TOMCAT SERVICE FILE
  template:
    src: templates/tomcat.service
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: START AND ENABLE TOMCAT
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

#- name: restart tomcat
#  notify: restart tomcat
